version: "3.9"

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./dev/random:/dev/random:ro
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${DB_NAME}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASS}
      MB_DB_HOST: postgres
      MB_JETTY_PORT: ${MB_JETTY_PORT}
    networks:
      - default
      - proxy # for proxy
      - dbnet # for db storage
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: metabase-db
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - default
      - dbnet # for db storage
    volumes:
      - mb_postgres_data:/var/lib/postgresql/data

networks:
  proxy:
    external: true
  dbnet:
    external: true

volumes:
  mb_postgres_data:
