version: '3'

services:
  caddy:
    container_name: caddy
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - ./data/:/data/
      - ./config/:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  proxy:
    external: true
