apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o ./helm
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: directus
  name: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: directus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o ./helm
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/directus: "true"
        io.kompose.network/proxy: "true"
        io.kompose.service: directus
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
            - name: CACHE_ENABLED
            - name: CACHE_REDIS
            - name: CACHE_STORE
            - name: DB_CLIENT
            - name: DB_DATABASE
            - name: DB_HOST
            - name: DB_PASSWORD
            - name: DB_PORT
            - name: DB_USER
            - name: EMAIL_SMTP_HOST
            - name: EMAIL_SMTP_IGNORE_TLS
            - name: EMAIL_SMTP_NAME
            - name: EMAIL_SMTP_PASSWORD
            - name: EMAIL_SMTP_PORT
            - name: EMAIL_SMTP_SECURE
            - name: EMAIL_SMTP_USER
            - name: EMAIL_TRANSPORT
            - name: KEY
            - name: LETSENCRYPT_EMAIL
            - name: LETSENCRYPT_HOST
            - name: PUBLIC_URL
            - name: SECRET
            - name: VIRTUAL_HOST
            - name: VIRTUAL_PORT
          image: directus/directus:latest
          name: directus
          ports:
            - containerPort: 8055
          resources: {}
          volumeMounts:
            - mountPath: /directus/uploads
              name: directus-claim0
            - mountPath: /directus/extensions
              name: directus-claim1
      restartPolicy: Always
      volumes:
        - name: directus-claim0
          persistentVolumeClaim:
            claimName: directus-claim0
        - name: directus-claim1
          persistentVolumeClaim:
            claimName: directus-claim1
status: {}
