version: '3'

services:
  strapi:
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASS}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - "1337:1337"
    volumes:
      - ./app:/srv/app
      - ./src:/src/arc
      - ./package.json:opt/package-json
      - ./yarn.lock:/opt/yarn.lock
      - strapi_uploads:/opt/app/public/uploads
    depends_on:
      - db
    networks:
      - default
      - proxy

  db:
    image: postgis/postgis:13-master
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default

networks:
  proxy:
    external: true

volumes:
  pg_data:
