version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
    volumes:
      - mariadb_data:/bitnami

  suitecrm:
    image: 'bitnami/suitecrm:latest'
    env_file: .env
    volumes:
      - 'suitecrm_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - proxy
      - default

volumes:
  mariadb_data:
  suitecrm_data:

networks:
  proxy:
    external: true
