version: '3.7'

services:
  traefik:
    container_name: traefik # Remove if using multiple instances
    networks:
      - proxy # Change if you're using another network
    labels:
      # Traefik configuration for the dashboard
      # Remove the labels section if the dashboard is disabled
      - traefik.http.routers.traefik-http.rule=Host(`traefik.example.com`)
      - traefik.http.routers.traefik-http.entrypoints=web
      - traefik.http.routers.traefik-http.middlewares=redirect
      - traefik.http.routers.traefik-https.rule=Host(`traefik.example.com`)
      - traefik.http.routers.traefik-https.entrypoints=websecure
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.middlewares=test-auth
      - traefik.http.routers.traefik-http.service=api@internal
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.test-auth.basicauth.users=admin:$$apr1$$f/gu0sNC$$bdbmTjvmb1iA3ZU/KWgiB1

networks:
  proxy:
    external: true
